services:
  - type: web
    name: game-analytics-api
    runtime: node
    region: singapore
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        sync: false
